/*
 * Copyright (C) 2017-2019 Dremio Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export const EXCLUDE_FROM_FUNCTIONS = ["LEFT", "CASE", "LIKE"] as const;

export const NULL_VALUE = "NULL";

export const RESERVED_TYPES = new Set(
  "VARBINARY BIT DATE FLOAT DOUBLE INTERVAL_DAY_SECONDS INTERVAL_YEAR_MONTHS INT BIGINT TIME TIMESTAMP VARCHAR LIST MAP STRUCT BOOL BOOLEAN BIT BLOB DECIMAL DOUBLE FLOAT LONG LONGBLOB LONGTEXT MEDIUM MEDIUMBLOB MEDIUMINT MEDIUMTEXT TIME TIMESTAMP TINYBLOB TINYINT TINYTEXT TEXT CLOB BIGINT INT INT2 INT8 INTEGER FLOAT DOUBLE CHAR VARCHAR DATE DATETIME YEAR UNSIGNED SIGNED NUMERIC REAL SECOND".split(
    " ",
  ),
);

export const RESERVED_WORDS = new Set(
  // copied from sabot/kernel/target/classes/sql-reserved-keywords.txt
  (
    "ABS ALL ALLOCATE ALLOW ALTER AND ANY ARE ARRAY ARRAY_MAX_CARDINALITY AS ASC ASENSITIVE ASYMMETRIC AT ATOMIC AUTHORIZATION AVG BEGIN BEGIN_FRAME BEGIN_PARTITION BETWEEN BIGINT BINARY BIT BLOB BOOLEAN BOTH BY CALL CALLED CARDINALITY CASCADED CASE CAST CEIL CEILING CHAR CHARACTER CHARACTER_LENGTH CHAR_LENGTH CHECK CLASSIFIER CLOB CLOSE COALESCE COLLATE COLLECT COLUMN COMMIT COMPACT CONDITION CONNECT CONSTRAINT CONTAINS CONVERT CORR CORRESPONDING COUNT COVAR_POP COVAR_SAMP CREATE CROSS CUBE CUME_DIST CURRENT CURRENT_CATALOG CURRENT_DATE CURRENT_DEFAULT_TRANSFORM_GROUP CURRENT_PATH CURRENT_ROLE CURRENT_ROW CURRENT_SCHEMA CURRENT_TIME CURRENT_TIMESTAMP CURRENT_TRANSFORM_GROUP_FOR_TYPE CURRENT_USER CURSOR CYCLE DATABASES DATE DAY DEALLOCATE DEC DECIMAL DECLARE DEFAULT DEFINE DELETE DESC DENSE_RANK DEREF DESCRIBE DETERMINISTIC DISALLOW DISCONNECT DISTINCT DOUBLE DROP DYNAMIC EACH ELEMENT ELSE EMPTY END END-EXEC END_FRAME END_PARTITION EQUALS ESCAPE EVERY EXCEPT EXEC EXECUTE EXISTS EXP EXPLAIN EXTEND EXTERNAL EXTRACT FALSE FETCH FILES FILTER FIRST_VALUE FLOAT FLOOR FOR FOREIGN FRAME_ROW FREE FROM FULL FUNCTION FUSION GET GLOBAL GRANT GROUP GROUPING GROUPS HAVING HOLD HOUR IDENTITY IF IMPORT IN INDICATOR INITIAL INNER INOUT INSENSITIVE INSERT INT INTEGER INTERSECT INTERSECTION INTERVAL INTO IS JOIN LAG LANGUAGE LARGE LAST_VALUE LATERAL LEAD LEADING LEFT LIKE LIKE_REGEX LIMIT LN LOAD LOCAL LOCALTIME LOCALTIMESTAMP LOWER MATCH MATCHES MATCH_NUMBER MATCH_RECOGNIZE MAX MEMBER MERGE METADATA METHOD MIN MINUS MINUTE MOD MODIFIES MODULE MONTH MULTISET NATIONAL NATURAL NCHAR NCLOB NEW NEXT NO NONE NORMALIZE NOT NTH_VALUE NTILE NULL NULLIF NUMERIC OCCURRENCES_REGEX OCTET_LENGTH OF OFFSET OLD OMIT ON ONE ONLY OPEN OR ORDER OUT OUTER OVER OVERLAPS OVERLAY PARAMETER PARTITION PATTERN PER PERCENT PERCENTILE_CONT PERCENTILE_DISC PERCENT_RANK PERIOD PERMUTE PORTION POSITION POSITION_REGEX POWER PRECEDES PRECISION PREPARE PREV PRIMARY PROCEDURE RANGE RANK READS REAL RECURSIVE REF REFERENCES REFERENCING REFRESH REGR_AVGX REGR_AVGY REGR_COUNT REGR_INTERCEPT REGR_R2 REGR_SLOPE REGR_SXX REGR_SXY REGR_SYY RELEASE RESET RESULT RETURN RETURNS REVOKE RIGHT ROLLBACK ROLLUP ROW ROWS ROW_NUMBER RUNNING SAVEPOINT SCHEMAS SCOPE SCROLL SEARCH SECOND SEEK SELECT SENSITIVE SESSION_USER SET SHOW SIMILAR SKIP SMALLINT SOME SPECIFIC SPECIFICTYPE SQL SQLEXCEPTION SQLSTATE SQLWARNING SQRT START STATIC STDDEV_POP STDDEV_SAMP STREAM SUBMULTISET SUBSET SUBSTRING SUBSTRING_REGEX SUCCEEDS SUM SYMMETRIC SYSTEM SYSTEM_TIME SYSTEM_USER TABLE TABLES TABLESAMPLE THEN TIME TIMESTAMP TIMEZONE_HOUR TIMEZONE_MINUTE TINYINT TO TRAILING TRANSLATE TRANSLATE_REGEX TRANSLATION TREAT TRIGGER TRIM TRIM_ARRAY TRUE TRUNCATE UESCAPE UNION UNIQUE UNKNOWN UNNEST UPDATE UPPER UPSERT USE USER USING VALUE VALUES VALUE_OF VARBINARY VARCHAR VARYING VAR_POP VAR_SAMP VERSIONING WHEN WHENEVER WHERE WIDTH_BUCKET WINDOW WITH WITHIN WITHOUT YEAR VIEW BRANCH ASSIGN" +
    // TYPES:
    // list from https://github.com/dremio/dremio/blob/master/sabot/logical/src/main/java/com/dremio/common/expression/CompleteType.java
    // minus null, late, object (internal types)
    " " +
    "VARBINARY BIT DATE FLOAT DOUBLE INTERVAL_DAY_SECONDS INTERVAL_YEAR_MONTHS INT BIGINT TIME TIMESTAMP VARCHAR" +
    // plus list, map, struct
    " " +
    "LIST MAP STRUCT" +
    // plus text/x-sqlite list from codemirror because we don't have a list of type aliases
    //    https://github.com/codemirror/CodeMirror/blob/master/mode/sql/sql.js
    //    Portions: CodeMirror, copyright (c) by Marijn Haverbeke and others
    //    Distributed under an MIT license: http://codemirror.net/LICENSE
    " " +
    "BOOL BOOLEAN BIT BLOB DECIMAL DOUBLE FLOAT LONG LONGBLOB LONGTEXT MEDIUM MEDIUMBLOB MEDIUMINT MEDIUMTEXT TIME TIMESTAMP TINYBLOB TINYINT TINYTEXT TEXT CLOB BIGINT INT INT2 INT8 INTEGER FLOAT DOUBLE CHAR VARCHAR DATE DATETIME YEAR UNSIGNED SIGNED NUMERIC REAL" +
    " " +
    "REPLACE TAG"
  )
    // todo: reconcile with constants/DataTypes.js, factor into independant list
    .split(" ")
    .filter((val) => val !== NULL_VALUE),
);
