/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/jobs-listing/v1.0": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              jobs: components["schemas"]["Job"][];
              next: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Dataset: {
      datasetName: string;
      datasetPath: string;
      datasetPathsList: unknown[];
      datasetType: string;
      versionContext: string;
    };
    DurationDetails: {
      phaseDuration: string;
      phaseName: "PENDING";
      phaseStartTime: string;
    };
    Job: {
      accelerated: boolean;
      datasetVersion: "UNKNOWN";
      description: string;
      duration: number;
      durationDetails: components["schemas"]["DurationDetails"][];
      endTime: number;
      /** Format: uuid */
      id: string;
      input: string;
      isComplete: boolean;
      output: string;
      outputLimited: boolean;
      outputRecords: number;
      /** Format: float */
      plannerEstimatedCost: number;
      queriedDatasets: components["schemas"]["Dataset"][];
      queryText: string;
      queryType: "METADATA_REFRESH";
      requestType: "RUN_SQL";
      rowsScanned: number;
      spilled: boolean;
      starFlakeAccelerated: boolean;
      startTime: number;
      state: "FAILED";
      totalAttempts: number;
      user: string;
      waitInClient: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
