/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/sql-runner/session": {
    get: {
      responses: {
        /** @description null */
        200: {
          content: {
            "application/json": components["schemas"]["SQLRunnerSession"];
          };
        };
      };
    };
    put: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["SQLRunnerSessionUpdate"];
        };
      };
      responses: {
        /** @description null */
        200: {
          content: {
            "application/json": components["schemas"]["SQLRunnerSession"];
          };
        };
      };
    };
  };
  "/sql-runner/session/tabs/{scriptId}": {
    put: {
      parameters: {
        path: {
          scriptId: string;
        };
      };
      responses: {
        /** @description Tab was successfully added to, or already exists in, the SQL runner session */
        200: {
          content: {
            "application/json": components["schemas"]["SQLRunnerSession"];
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          scriptId: string;
        };
      };
      responses: {
        /** @description Tab was successfully removed from, or already no longer exists in, the SQL runner session */
        204: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    SQLRunnerSession: {
      /** Format: uuid */
      currentScriptId: string;
      /** Format: date-time */
      modifiedAt: string;
      scriptIds: string[];
      /** Format: uuid */
      userId: string;
    };
    SQLRunnerSessionUpdate: {
      /** Format: uuid */
      currentScriptId: string;
      scriptIds: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
