/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description An RFC 9457 problem object */
    Problem: {
      /**
       * Format: uri-reference
       * @description A URI reference that identifies the problem type
       */
      type: string;
      /** @description The HTTP status code generated by the origin server for this occurrence of the problem */
      status?: number;
      /** @description A human-readable summary of the problem type */
      title?: string;
      /** @description An optional extension containing non-standard meta-information for the given error type */
      meta?: {
        additionalDetails?: components["schemas"]["AdditionalDetails"][];
      };
    };
    ValidationProblem: {
      /** @constant */
      type: "https://api.dremio.dev/problems/validation-problem";
      /** @constant */
      title?: "There was a problem validating the content of the request";
      /** @constant */
      status?: 422;
      /** @description An extension containing multiple validation or request errors */
      errors: {
          type: components["schemas"]["Problem"]["type"];
          /**
           * Format: relative-json-pointer
           * @description A JSON pointer to locate the problem within the request's content
           */
          pointer: string;
          detail?: string;
        }[];
    };
    /** @description Additional information not controlled by Dremio that could be relevant to the API consumer / UI user */
    AdditionalDetails: {
      contents: string;
      subject: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
