/*
 * Copyright (C) 2017-2019 Dremio Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dremio.service.tokens.jwt;

import java.util.Date;
import org.immutables.value.Value.Immutable;

/** A JSON Web Token that is generated by Dremio. */
@Immutable
public interface JWTClaims {
  /** ID of the JWT. Corresponds to the "jti" claim. */
  String getJWTId();

  /** Entity who issued the JWT. Corresponds to the "iss" claim. */
  String getIssuer();

  /** Subject of the JWT (e.g. Dremio user ID). Corresponds to the "sub" claim. */
  String getSubject();

  /** Audience the JWT is intended for. Corresponds to the "aud" claim. */
  String getAudience();

  /** Time that this JWT expires. Corresponds to the "exp" claim. */
  Date getExpirationTime();

  /** Time that the JWT first becomes valid. Corresponds to the "nbf" claim. */
  Date getNotBeforeTime();

  /** Time that the JWT was issued. Corresponds to the "iat" claim. */
  Date getIssueTime();
}
