// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pOVQPOOOOQO'#C_'#C_OOQO'#Cd'#CdO_QPO'#C`OOQO'#C^'#C^QjQPOOOOQO-E6b-E6bOVQPO'#CaOOQO'#Ce'#CeQjQPOOOOQO'#Cc'#CcOOQO,58{,58{OOQO-E6c-E6c",
  stateData: "r~O[OS~O]PO^QO~O^QOUSXYSX~OUVO~OU^~",
  goto: "xYPPZ^^dPhkrRTOQSORYVTWTXRZVSROVRURQXTR[X",
  nodeNames: "⚠ DremioSemanticSearch SearchText QuotedString UnquotedString Filter FilterKeyword FilterValue",
  maxTerm: 14,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "%o~R]X^zpqzrs!o!c!}%X#T#o%X#y#zz$f$gz#BY#BZz$IS$I_z$I|$JOz$JT$JUz$KV$KWz&FU&FVz~!PY[~X^zpqz#y#zz$f$gz#BY#BZz$IS$I_z$I|$JOz$JT$JUz$KV$KWz&FU&FVz~!rWpq!oqr!ors#[s#O!o#O#P#a#P;'S!o;'S;=`%R<%lO!o~#aO]~~#dXrs!o!P!Q!o#O#P!o#U#V!o#Y#Z!o#b#c!o#f#g!o#h#i!o#i#j$P~$SR!Q![$]!c!i$]#T#Z$]~$`R!Q![$i!c!i$i#T#Z$i~$lR!Q![$u!c!i$u#T#Z$u~$xR!Q![!o!c!i!o#T#Z!o~%UP;=`<%l!o~%^S^~!Q![%X![!]%j!c!}%X#T#o%X~%oOU~",
  tokenizers: [0],
  topRules: {"DremioSemanticSearch":[0,1]},
  tokenPrec: 31
})
