// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  DremioSemanticSearch = 1,
  SearchText = 2,
  QuotedString = 3,
  UnquotedString = 4,
  Filter = 5,
  FilterKeyword = 6,
  FilterValue = 7
