/*
 * Copyright (C) 2017-2019 Dremio Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dremio.exec.store.iceberg;

public class DremioViewVersionMetadataParserHelper {

  public static final String validJson =
      "{\n"
          + "  \"format-version\" : 1,\n"
          + "  \"location\" : \"s3://bucket/test/location\",\n"
          + "  \"current-version-id\" : 1,\n"
          + "  \"properties\" : {\n"
          + "    \"some-key\" : \"some-value\"\n"
          + "  },\n"
          + "  \"versions\" : [ {\n"
          + "    \"version-id\" : 1,\n"
          + "    \"parent-version-id\" : 1,\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"summary\" : {\n"
          + "      \"operation\" : \"N/A\",\n"
          + "      \"genie_id\" : \"N/A\",\n"
          + "      \"engine_version\" : \"N/A\"\n"
          + "    },\n"
          + "    \"view-definition\" : {\n"
          + "      \"sql\" : \"select * from mySource.myTable\",\n"
          + "      \"schema\" : {\n"
          + "        \"type\" : \"struct\",\n"
          + "        \"schema-id\" : 0,\n"
          + "        \"fields\" : [ {\n"
          + "          \"id\" : 1,\n"
          + "          \"name\" : \"x\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        }, {\n"
          + "          \"id\" : 2,\n"
          + "          \"name\" : \"y\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\",\n"
          + "          \"doc\" : \"comment\"\n"
          + "        }, {\n"
          + "          \"id\" : 3,\n"
          + "          \"name\" : \"z\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        } ]\n"
          + "      },\n"
          + "      \"sessionCatalog\" : \"session-catalog\",\n"
          + "      \"sessionNamespace\" : [ \"session-namespace\" ]\n"
          + "    }\n"
          + "  } ],\n"
          + "  \"version-log\" : [ {\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"version-id\" : 1\n"
          + "  } ]\n"
          + "}";

  public static final String jsonInvalidFormatVersion =
      "{\n"
          + "  \"format-version\" : 5,\n"
          + "  \"location\" : \"s3://bucket/test/location\",\n"
          + "  \"current-version-id\" : 1,\n"
          + "  \"properties\" : {\n"
          + "    \"some-key\" : \"some-value\"\n"
          + "  },\n"
          + "  \"versions\" : [ {\n"
          + "    \"version-id\" : 1,\n"
          + "    \"parent-version-id\" : 1,\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"summary\" : {\n"
          + "      \"operation\" : \"N/A\",\n"
          + "      \"genie_id\" : \"N/A\",\n"
          + "      \"engine_version\" : \"N/A\"\n"
          + "    },\n"
          + "    \"view-definition\" : {\n"
          + "      \"sql\" : \"select * from mySource.myTable\",\n"
          + "      \"schema\" : {\n"
          + "        \"type\" : \"struct\",\n"
          + "        \"schema-id\" : 0,\n"
          + "        \"fields\" : [ {\n"
          + "          \"id\" : 1,\n"
          + "          \"name\" : \"x\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        }, {\n"
          + "          \"id\" : 2,\n"
          + "          \"name\" : \"y\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\",\n"
          + "          \"doc\" : \"comment\"\n"
          + "        }, {\n"
          + "          \"id\" : 3,\n"
          + "          \"name\" : \"z\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        } ]\n"
          + "      },\n"
          + "      \"sessionCatalog\" : \"session-catalog\",\n"
          + "      \"sessionNamespace\" : [ \"session-namespace\" ]\n"
          + "    }\n"
          + "  } ],\n"
          + "  \"version-log\" : [ {\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"version-id\" : 1\n"
          + "  } ]\n"
          + "}";

  public static final String jsonMissingLocation =
      "{\n"
          + "  \"format-version\" : 1,\n"
          + "  \"current-version-id\" : 1,\n"
          + "  \"properties\" : {\n"
          + "    \"some-key\" : \"some-value\"\n"
          + "  },\n"
          + "  \"versions\" : [ {\n"
          + "    \"version-id\" : 1,\n"
          + "    \"parent-version-id\" : 1,\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"summary\" : {\n"
          + "      \"operation\" : \"N/A\",\n"
          + "      \"genie_id\" : \"N/A\",\n"
          + "      \"engine_version\" : \"N/A\"\n"
          + "    },\n"
          + "    \"view-definition\" : {\n"
          + "      \"sql\" : \"select * from mySource.myTable\",\n"
          + "      \"schema\" : {\n"
          + "        \"type\" : \"struct\",\n"
          + "        \"schema-id\" : 0,\n"
          + "        \"fields\" : [ {\n"
          + "          \"id\" : 1,\n"
          + "          \"name\" : \"x\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        }, {\n"
          + "          \"id\" : 2,\n"
          + "          \"name\" : \"y\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\",\n"
          + "          \"doc\" : \"comment\"\n"
          + "        }, {\n"
          + "          \"id\" : 3,\n"
          + "          \"name\" : \"z\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        } ]\n"
          + "      },\n"
          + "      \"sessionCatalog\" : \"session-catalog\",\n"
          + "      \"sessionNamespace\" : [ \"session-namespace\" ]\n"
          + "    }\n"
          + "  } ],\n"
          + "  \"version-log\" : [ {\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"version-id\" : 1\n"
          + "  } ]\n"
          + "}";

  public static final String jsonMissingCurrentVersionId =
      "{\n"
          + "  \"format-version\" : 1,\n"
          + "  \"location\" : \"s3://bucket/test/location\",\n"
          + "  \"properties\" : {\n"
          + "    \"some-key\" : \"some-value\"\n"
          + "  },\n"
          + "  \"versions\" : [ {\n"
          + "    \"version-id\" : 1,\n"
          + "    \"parent-version-id\" : 1,\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"summary\" : {\n"
          + "      \"operation\" : \"N/A\",\n"
          + "      \"genie_id\" : \"N/A\",\n"
          + "      \"engine_version\" : \"N/A\"\n"
          + "    },\n"
          + "    \"view-definition\" : {\n"
          + "      \"sql\" : \"select * from mySource.myTable\",\n"
          + "      \"schema\" : {\n"
          + "        \"type\" : \"struct\",\n"
          + "        \"schema-id\" : 0,\n"
          + "        \"fields\" : [ {\n"
          + "          \"id\" : 1,\n"
          + "          \"name\" : \"x\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        }, {\n"
          + "          \"id\" : 2,\n"
          + "          \"name\" : \"y\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\",\n"
          + "          \"doc\" : \"comment\"\n"
          + "        }, {\n"
          + "          \"id\" : 3,\n"
          + "          \"name\" : \"z\",\n"
          + "          \"required\" : true,\n"
          + "          \"type\" : \"long\"\n"
          + "        } ]\n"
          + "      },\n"
          + "      \"sessionCatalog\" : \"session-catalog\",\n"
          + "      \"sessionNamespace\" : [ \"session-namespace\" ]\n"
          + "    }\n"
          + "  } ],\n"
          + "  \"version-log\" : [ {\n"
          + "    \"timestamp-ms\" : 1,\n"
          + "    \"version-id\" : 1\n"
          + "  } ]\n"
          + "}";
}
