/*
 * Copyright (C) 2017-2019 Dremio Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dremio.service.jobs;

import static com.dremio.service.job.proto.QueryLabel.COPY;
import static com.dremio.service.job.proto.QueryLabel.CTAS;
import static com.dremio.service.job.proto.QueryLabel.DML;
import static com.dremio.service.job.proto.QueryLabel.NONE;
import static com.dremio.service.job.proto.QueryLabel.OPTIMIZATION;

import com.dremio.service.job.proto.QueryLabel;
import com.google.common.base.Strings;

/** Utility class for query label. */
final class QueryLabelUtils {

  private QueryLabelUtils() {}

  /**
   * If the query is submitted by services internally, and not by a user action.
   *
   * @param queryLabel query Label
   * @return iff the query is generated by services internally
   */
  static boolean isInternal(final QueryLabel queryLabel) {
    // TODO: determaine what will be considered. Placeholder for now and COPY and OPTIMIZATION are
    // considered internal
    switch (queryLabel) {
      case COPY:
      case DML:
      case OPTIMIZATION:
      case CTAS:
        return true;
      default:
        return false;
    }
  }

  /**
   * Get string name for this query label.
   *
   * @param queryLabel query Label
   * @return Query Label String
   */
  public static String getQueryLabelString(final QueryLabel queryLabel) {
    if (queryLabel == null) {
      return "NONE";
    }
    switch (queryLabel) {
      case CTAS:
        return "CTAS";
      case OPTIMIZATION:
        return "OPTIMIZATION";
      case COPY:
        return "COPY";
      case DML:
        return "DML";
      default:
        return "NONE";
    }
  }

  /**
   * Get string name for this query label.
   *
   * @param queryLabel query Label
   * @return Query Label String
   */
  public static QueryLabel getQueryLabelFromString(final String queryLabel) {
    if (Strings.isNullOrEmpty(queryLabel)) {
      return NONE;
    }
    switch (queryLabel) {
      case "CTAS":
        return CTAS;
      case "OPTIMIZATION":
        return OPTIMIZATION;
      case "COPY":
        return COPY;
      case "DML":
        return DML;
      default:
        return NONE;
    }
  }
}
